In [1]:
import numpy as np
import pandas as pd

In [2]:
dict1 = {
    "name": ["kirti", "peter", "sam", "shubh"],
    "marks": [92, 93, 31, 86],
    "city": ["delhi", "calfornia", "goa", "chandigarh"]
}

In [3]:
df = pd.DataFrame(dict1)

In [4]:
print(df)

    name  marks        city
0  kirti     92       delhi
1  peter     93   calfornia
2    sam     31         goa
3  shubh     86  chandigarh

In [6]:
df.to_csv('data.csv')
df.to_csv('data_without_index.csv', index=False)

In [7]:
df.head(2)

    name  marks       city
0  kirti     92      delhi
1  peter     93  calfornia

In [8]:
df.tail(2)

    name  marks        city
2    sam     31         goa
3  shubh     86  chandigarh

In [9]:
df.describe()

           marks
count   4.000000
mean   75.500000
std    29.827281
min    31.000000
25%    72.250000
50%    89.000000
75%    92.250000
max    93.000000

In [10]:
trains = pd.read_csv('trains.csv')

In [11]:
trains

   Unnamed: 0  Train No.  speed        city
0           0      12238     62       delhi
1           1      38265     28   calfornia
2           2      98542     31         goa
3           3      17662     86  chandigarh

In [12]:
trains['speed'][0] = 50

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_20068\3155761661.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  trains['speed'][0] = 50
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_20068\3155761661.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trains['speed'][0] = 50

In [13]:
trains

   Unnamed: 0  Train No.  speed        city
0           0      12238     50       delhi
1           1      38265     28   calfornia
2           2      98542     31         goa
3           3      17662     86  chandigarh

In [14]:
trains.to_csv('trains.csv')

In [15]:
trains.index = ["first", "second", "third", " fourth"]
trains

         Unnamed: 0  Train No.  speed        city
first             0      12238     50       delhi
second            1      38265     28   calfornia
third             2      98542     31         goa
 fourth           3      17662     86  chandigarh

In [ ]:
ser = pd.Series(np.random.rand(34))
print(type(ser))
ser

0     0.603604
1     0.195042
2     0.348053
3     0.009911
4     0.058927
5     0.946390
6     0.799794
7     0.198939
8     0.049478
9     0.065732
10    0.994934
11    0.408368
12    0.171844
13    0.985407
14    0.824760
15    0.804682
16    0.514042
17    0.332220
18    0.530766
19    0.258351
20    0.361441
21    0.293776
22    0.208543
23    0.378789
24    0.383359
25    0.953663
26    0.805844
27    0.934136
28    0.954214
29    0.313667
30    0.736953
31    0.440998
32    0.171363
33    0.518923
dtype: float64